---
name: Validate

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '**'

jobs:
  generated-files-commited:
    name: Generated files are commited
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisites
        env:
          GO111MODULE: on
        run: go get github.com/mikefarah/yq/v3

      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate release files
        run: make release-files

      - name: Check if everything is consistent
        run: git diff --exit-code
