---
name: Validate

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '**'

jobs:
  generated-files-commited:
    name: Generated files are commited
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate release files
        run: make release-files
        uses: mikefarah/yq@3.4.0

      - name: Check if everything is consistent
        run: git diff --exit-code
